# Generated by Django 3.2.9 on 2022-02-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='addedby_user_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='muser',
            name='reference_tablestatus_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='muser_tablestatus', to='register.mreference'),
        ),
    ]
