# Generated by Django 3.2.9 on 2022-03-22 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20220214_1428'),
        ('register', '0003_muser_momo'),
    ]

    operations = [
    ]
