# Generated by Django 3.2.9 on 2022-03-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bo', '0001_initial'),
        ('register', '0004_merge_0002_auto_20220214_1428_0003_muser_momo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='reference_tablestatus_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='muser_tablestatus', to='bo.mreference'),
        ),
        migrations.DeleteModel(
            name='MReference',
        ),
    ]
