# Generated by Django 3.2.9 on 2022-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20220331_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='muser',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
